#page title
page_title: DestiWake # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6736437794 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: https://testflight.apple.com/join/7uqk2qEQ # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/apps/internaltest/4701585620336993341

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: DestiWake - Smart Travel Alarm # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Reach out to us to signup for the closed beta.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Chunky Tofu Studios
your_link: https://chunkytofustudios.com
your_city: Princeton & Dublin
email_address: support@chunkytofustudios.com
facebook_username: chunkytofustudios
instagram_username: chunkytofustudios
twitter_username: Chunky_Tofu
github_username: ChunkyTofuStudios
youtube_username:
mastodon_link:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Set Your Wake-Up Alert
    description: Sleep without worries on your commute. Just enter your departure and destination stations, set how many minutes before arrival you want to wake up, and enjoy your rest. Our app ensures you wake up refreshed and on time, every time.
    fontawesome_icon_name: moon

  - title: Live Journey Tracking
    description: Watch your journey unfold in real time. Our app uses GPS to show your current location on a map, so you can see exactly where you are and how far you are from your destination. Travel stress-free, knowing you won’t miss your stop.
    fontawesome_icon_name: map-marker

  - title: Service Updates and Notifications
    description: Stay informed on the go. Receive real-time updates about delays, cancellations, and service changes directly within the app. Never be caught off guard by transit disruptions again.
    fontawesome_icon_name: bell

  - title: Customizable Alerts
    description: Choose how you wake up. Select your favorite tune or vibration pattern for your alerts. Customize how and when you are notified about approaching your final stop, so waking up is pleasant and reliable.
    fontawesome_icon_name: clock

  - title: Trip History and Management
    description: Manage your commutes effortlessly. Save your frequent routes and access past trips with a simple tap. Plan your weekly commutes in advance and modify them as your schedule changes.
    fontawesome_icon_name: history

  - title: Available on iOS and Android
    description: Access anywhere, anytime. Whether you’re an iPhone devotee or an Android enthusiast, our app works seamlessly across platforms, so you can count on us no matter what device you use.
    fontawesome_icon_name: mobile

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
